export interface SignatureLocation {
  id: string;
  pageIndex: number; // 0-based
  x: number; // Normalized 0-1
  y: number; // Normalized 0-1
  width: number; // Normalized 0-1
  height: number; // Normalized 0-1
  value?: string; // Base64 signature image
}

export interface DocumentMetadata {
  id: string;
  title: string;
  filename: string;
  uploadDate: string;
  status: 'unsigned' | 'signed';
  description?: string; // Generated by Gemini
  tags?: string[]; // Generated by Gemini
  originalPdfData: string; // Base64
  signedPdfData?: string; // Base64
  signatures: SignatureLocation[];
}

export interface ToastMessage {
  id: string;
  type: 'success' | 'error' | 'info';
  message: string;
}

export enum AppView {
  DASHBOARD = 'DASHBOARD',
  SIGNING = 'SIGNING',
}