import React, { useState, useRef } from 'react';
import { X, UploadCloud, Loader2 } from 'lucide-react';
import { fileToBase64, extractTextFromFirstPage, scanForSignatures } from '../services/pdfUtils';
import { analyzeDocumentContent } from '../services/geminiService';
import { saveDocument } from '../services/storageService';
import { DocumentMetadata } from '../types';

interface UploadModalProps {
  onClose: () => void;
  onUploadComplete: () => void;
}

const UploadModal: React.FC<UploadModalProps> = ({ onClose, onUploadComplete }) => {
  const [isProcessing, setIsProcessing] = useState(false);
  const [statusText, setStatusText] = useState('');
  const fileInputRef = useRef<HTMLInputElement>(null);

  const handleFileChange = async (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;

    if (file.type !== 'application/pdf') {
      alert("Please upload a PDF file.");
      return;
    }

    setIsProcessing(true);
    setStatusText('Reading file...');

    try {
      // 1. Convert to Base64
      const base64 = await fileToBase64(file);

      // 2. Scan for "$signature"
      setStatusText('Scanning for signature fields...');
      const signatures = await scanForSignatures(base64);
      console.log(`Found ${signatures.length} signature fields.`);

      // 3. Extract Text & Gemini Analysis
      setStatusText('Analyzing content with Gemini AI...');
      const textContent = await extractTextFromFirstPage(base64);
      const metadata = await analyzeDocumentContent(textContent);

      // 4. Create Document Object
      const newDoc: DocumentMetadata = {
        id: crypto.randomUUID(),
        title: metadata.title,
        filename: file.name,
        description: metadata.summary,
        tags: metadata.tags,
        uploadDate: new Date().toISOString(),
        status: 'unsigned',
        originalPdfData: base64,
        signatures: signatures,
      };

      // 5. Save
      setStatusText('Saving...');
      saveDocument(newDoc);

      onUploadComplete();
    } catch (error) {
      console.error(error);
      alert("Failed to process document. See console.");
    } finally {
      setIsProcessing(false);
    }
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 backdrop-blur-sm p-4">
      <div className="bg-white rounded-2xl w-full max-w-lg shadow-2xl overflow-hidden relative">
        <button 
          onClick={onClose}
          className="absolute top-4 right-4 p-2 rounded-full hover:bg-gray-100 text-gray-500"
          disabled={isProcessing}
        >
          <X size={20} />
        </button>

        <div className="p-8 text-center">
          <div className="w-16 h-16 bg-brand-50 text-brand-600 rounded-full flex items-center justify-center mx-auto mb-6">
            {isProcessing ? <Loader2 className="animate-spin" size={32} /> : <UploadCloud size={32} />}
          </div>

          <h2 className="text-2xl font-bold text-gray-900 mb-2">
            {isProcessing ? 'Processing Document' : 'Upload PDF'}
          </h2>
          
          <p className="text-gray-500 mb-8">
            {isProcessing 
              ? statusText 
              : 'Select a PDF document. We will automatically detect signature fields ($signature) and analyze the content.'}
          </p>

          {!isProcessing && (
            <div className="space-y-4">
              <button
                onClick={() => fileInputRef.current?.click()}
                className="w-full bg-brand-600 hover:bg-brand-700 text-white font-bold py-3 px-6 rounded-xl transition-all active:scale-95"
              >
                Choose File
              </button>
              <input
                type="file"
                ref={fileInputRef}
                className="hidden"
                accept="application/pdf"
                onChange={handleFileChange}
              />
              <p className="text-xs text-gray-400">
                Processed locally. Metadata generated by Gemini.
              </p>
            </div>
          )}
        </div>
        
        {isProcessing && (
          <div className="h-2 bg-gray-100 w-full">
            <div className="h-full bg-brand-500 animate-pulse w-full"></div>
          </div>
        )}
      </div>
    </div>
  );
};

export default UploadModal;